### ISSUE TITLE
能否支持跨屏截图

### ISSUE THREAD

**Issue by a471640241** [xiaou66/shortcut-capture#2]
两台显示器，只有主显示器能够截图，即使我把utools放在第二个显示器，也没办法截图

**Comment by xiaou66** [comment]
在 uTools 官方下载最新版 uTools

**Comment by xiaou66** [comment]
> 两台显示器，只有主显示器能够截图，即使我把utools放在第二个显示器，也没办法截图

在 uTools 官方下载最新版 uTools

**Comment by a471640241** [comment]
好的，感谢，可以了
